travis:
  secure:
    BINSTAR_TOKEN: XFNKDcegUNY1LTQjoh4VDT5NTHJBBnyJnstsYAxXZ/29bvmUtNZ1/qfkh06W81g4M9fjUy3ySb9Xj5k+sdFz2wtIXzwtlCdMSnC5MAwP/kgvjM9AzVlAg5J/2It5Lk34Q0vTM1UNDD9q0fk8AG8moTJk9+TjrQaJgCSKFp4mmtz1KR+LUd8vBWpsyBh7Abx2lycah2kI3k4Wvr3RhegPXDu6t1vVwaik27reya0K/+mFHJYR8+z6ajdfYMiaATD/0tdddfkQa5Ge+WNtlb8kBanU1lGJ2r5sxWdgPmDWvz2qdgKuWZVH+CYI9qrazHuoRKOdV5PO7XF6/9KcZmZ+YmjYlGA0mSL1kynxK97HwG4D2O8B4wKpcDwWzzYLsQ2tP+kTLJhfafDJi40gTOl7bX5lgu7fI6UoSUShhTCeSv3FISIPRXN1pRB1cFgqPjUjLJ2T2WFFWZUdUtbxy69oZdSOOFS8FqsB9lj8atDLfoAXYvH+SzWm9JGz2X6RfY8rh/Bn4SQ+tGdHD6cwGbOo0qNGTEWlZtPmmmU6OXTj/Nqt7w/lcJNRWIBSG1OOmAsw87WnJ8vLBOVkWhpHL3aM8tLZgfAyaKJFFyzoDQm5/dZqT/QBctsgllkdQgyeIDsxc6OSjye6m58MmNNhBIb37qQGvZUR4pKvnXX88tTvARw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
